{
"app_id": "wxe6f8d0fb885f2cc9",
"app_secret": "87f478ce0c69a5d0cfee7a9a9847273e",
"template_id": "2DRgIop3CGvnzieuUazR_XK-dWUlO5vrZs3iC2Tsdg8",
"user": ["orZ-s54UQyiPJUAIIf2Fkx_7oiHA","orZ-s50uSackGu8pSiHbWZGoLw94"],
 

"weather_key": "bd96c4806e9e40509ed1a4b092dd22dd",
"region": "青岛市",
"birthday1": {"name": "荣玉浩", "birthday": "2001-03-06"},
# 生日2
"birthday2": {"name": "刘巧巧", "birthday": "2000-02-08"},
"love_date": "2020-10-25",
"note_ch": "",
"note_en": ""
}
